### ISSUE TITLE
CloudFormation Outputs.ApplicationOutputName is not available

### ISSUE THREAD

**Issue by 0xjjoyy** [aws-samples/aws-secrets-manager-rotation-lambdas#11]
Using the AWS Serverless Application Repository with both the AWS Serverless Application Module and AWS CloudFormation seems to be missing the Outputs.ApplicationOutputName as specified in the [Return values documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapplication).

I've include the AWS CloudFormation which I used.

```
  rDatabaseCredentialRotationApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: 'arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser'
        SemanticVersion: 1.0.0
      Parameters:
        endpoint: !Sub 'https://secretsmanager.${AWS::Region}.amazonaws.com'
```

The generated nested stack is included below.

```

AWSTemplateFormatVersion: 2010-09-09
Parameters:
  endpoint:
    Type: String
    Description: The Secrets Manager endpoint to hit
Resources:
  SecretsManagerRDSMySQLRotationSingleUser:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: awsserverlessrepo-changesets-CHANGESET-ID-HERE
        S3Key: KEY-HERE
      Description: >-
        Conducts an AWS SecretsManager secret rotation for RDS MySQL using
        single user rotation scheme
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
      Environment:
        Variables:
          SECRETS_MANAGER_ENDPOINT: !Ref endpoint
          AWS_DATA_PATH: models
      Handler: lambda_function.lambda_handler
      Role: !GetAtt 
        - SecretsManagerRDSMySQLRotationSingleUserRole
        - Arn
      Timeout: 30
      Runtime: python2.7
  SecretsManagerRDSMySQLRotationSingleUserRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: SecretsManagerRDSMySQLRotationSingleUserRolePolicy0
          PolicyDocument:
            Statement:
              - Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DetachNetworkInterface'
                Resource: !Sub >-
                  arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

```

**Comment by 0xjjoyy** [comment]
Need to use latest SemanticVersion
```

  SecretsManagerRDSMySQLRotationSingleUser:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser
        SemanticVersion: 1.0.86
      Parameters: 
        # The Secrets Manager endpoint to hit
        endpoint: YOUR_VALUE
        # The name of the lambda function
        functionName: YOUR_VALUE
        # List of VPC security grouop IDs
        # vpcSecurityGroupIds: '' # Uncomment to override default value
        # List of VPC subnet IDs
        # vpcSubnetIds: '' # Uncomment to override default value  



```
