### ISSUE TITLE
Parameters: [vpcSecurityGroupIds, functionName, vpcSubnetIds] do not exist in the template when using CloudFormation

### ISSUE THREAD

**Issue by 0xjjoyy** [aws-samples/aws-secrets-manager-rotation-lambdas#12]
When using AWS CloudFormation with the AWS Serverless Application Module and the  AWS Serverless Application Repository, the paramter functionname is not recognized. However, it's listed in the docs for [To create a Lambda rotation function by using an AWS Serverless Application Repository template](https://docs.aws.amazon.com/secretsmanager/latest/userguide/enable-rotation-rds.html)

    endpoint – The URL of the service endpoint that you want the rotation function to query. Typically, this is https://secretsmanager.region.amazonaws.com.

    functionname – The name of the completed Lambda rotation function that's created by this process.

AWS CloudFormation template is included below.

```
  rDatabaseCredentialRotationApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        #https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html
        ApplicationId: 'arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser'
        SemanticVersion: 1.0.0
      Parameters:
        endpoint: !Sub 'https://secretsmanager.${AWS::Region}.amazonaws.com'
        functionname: 'test-function-name'
```

**Comment by 0xjjoyy** [comment]
Need to use the latest Semantic Version.

When using the 'Copy as SAM Resource',  the copied template is below.

```
  SecretsManagerRDSMySQLRotationSingleUser:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser
        SemanticVersion: 1.0.86
      Parameters: 
        # The Secrets Manager endpoint to hit
        endpoint: YOUR_VALUE
        # The name of the lambda function
        functionName: YOUR_VALUE
        # List of VPC security grouop IDs
        # vpcSecurityGroupIds: '' # Uncomment to override default value
        # List of VPC subnet IDs
        # vpcSubnetIds: '' # Uncomment to override default value  
```
