### ISSUE TITLE
Would be nice to be able to change the Runtime for the rotation function

### ISSUE THREAD

**Issue by umairrahmad** [aws-samples/aws-secrets-manager-rotation-lambdas#62]
Here is the yaml configuration for deploying the AWS::Serverless::Application

```
  RDSSecretRotationService:
    Type: "AWS::Serverless::Application"
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:region:id:applications/SecretsManagerRDSPostgreSQLRotationSingleUser
        SemanticVersion: 1.0.117
      Parameters:
        endpoint: !Sub "https://secretsmanager.${AWS::Region}.${AWS::URLSuffix}"
        functionName:
          Fn::Join:
            - ""
            - - Fn::ImportValue: !Sub ${ClusterImportPrefix}-ClusterResolvingName
              - "-rds-rotation-lambda"
        vpcSubnetIds:
          Fn::ImportValue: !Sub ${VPCImportPrefix}-PrivateSubnets
        vpcSecurityGroupIds: !Ref RDSSecurityGroup
```

where can the documentation for the parameter list supported by this AWS resource (AWS::serverless::application)

I tried to add both 

```
        Runtime: "python3.7"
        runtime: "python3.7"
```

failed to do so
