### ISSUE TITLE
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'pg'

### ISSUE THREAD

**Issue by hemantproTR** [aws-samples/aws-secrets-manager-rotation-lambdas#68]
Hi, in CloudWatch getting this error:

<html>
<body>

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'pg'
Traceback (most recent call last):
--

**Comment by whygoyal** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by babuknb** [comment]
Please let us know if any updates. Thanks.

**Comment by nomadme** [comment]
@whygoyal Any update on this?

**Comment by Monikaa7** [comment]
I had the same issue with pymysql, fixed it by installing the package and zipping it with the function itself. You can follow up the AWS documentation for this - https://docs.aws.amazon.com/lambda/latest/dg/python-package.html

**Comment by veelenga** [comment]
Is there anything required in order to fix this problem when lambda is deployed as part of [RotationSchedule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html#cfn-secretsmanager-rotationschedule-hostedrotationlambda)

```yml
RotationSchedule:
  Type: AWS::SecretsManager::RotationSchedule
  Properties:
    HostedRotationLambda:
      RotationLambdaName: DBSecretRotationScheduleLambda
      RotationType: PostgreSQLSingleUser
      # ...
```

Logged error message is basically the same: 

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named '_pg'
```
